import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import OCFContext from '../context/ocfc'

import WalletConnected from '../components/WalletConnected'
import CarouselNavigation from '../components/CarouselNavigation'

import Header from '../containers/header'

export default function Home() {
  const OCFC = useContext(OCFContext);

  if (!OCFC) return null;

  const { account, contract, isWalletConnected, connectWallet, mintMember, createFight, joinAndFight, trainFighter, withdraw } = OCFC;

  const carouselElements = [
    {
      title: 'Create Fight',
      onCLick: () => []
    },
    {
      title: 'Join Fight',
      onCLick: () => []
    },
    {
      title: 'Train Fighter',
      onCLick: () => []
    },
    {
      title: 'Withdraw',
      onCLick: () => []
    },
  ];


  return (
    <div>
      <Head>
        <title>OnChain Fight Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='background min-h-screen pt-20'>
        <div className='mt-5'>
          <CarouselNavigation elements={carouselElements} />
        </div>
      </main>
    </div >
  )
}
