import Head from 'next/head'
import { useContext, useState } from 'react'
import OCFContext from '../../context/ocfc'
import { ActiveTabContext } from '../../context/activeTab'
import CarouselNavigation from '../../components/CarouselNavigation'
import Header from '../../containers/header'

import { tabElements } from '../../constants'

export default function Home() {
  const OCFC = useContext(OCFContext);
  const ActiveTab = useContext(ActiveTabContext);

  if (!OCFC) return null;
  if (!ActiveTab) return null;

  const { account, getBalance, mintMember, createFight, joinAndFight, isAlreadyMember } = OCFC;
  const { activeTabIndex, changeActiveTabIndex } = ActiveTab;



  return (
    <div>
      <Head>
        <title>OnChain Fight Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='background min-h-screen pt-20'>
        <div className='mt-5'>
          <CarouselNavigation
            elements={tabElements}
            activeTabIndex={activeTabIndex}
            changeActiveTabIndex={changeActiveTabIndex}
          />
        </div>

      </main>
    </div >
  )
}
