import Head from 'next/head'
import { useContext } from 'react'
import { ActiveTabContext } from '../../context/activeTab'
import CarouselNavigation from '../../components/CarouselNavigation'
import Header from '../../containers/header'

import { tablist } from '../../constants'

import { withToast } from '../../hocs/withToast'

const Home = () => {
  const ActiveTab = useContext(ActiveTabContext);

  if (!ActiveTab) return null;

  const { activeTabIndex, changeActiveTabIndex } = ActiveTab;

  return (
    <div>
      <Head>
        <title>OnChain Fight Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <body className='background min-h-screen pt-20'>
        <div className='mt-12'>
          <CarouselNavigation
            titles={tablist.map((tab) => tab.title)}
            activeTabIndex={activeTabIndex}
            changeActiveTabIndex={changeActiveTabIndex}
          />
        </div>
        <main>
          {tablist[activeTabIndex]?.component || <div>Not Found</div>}
        </main>
      </body>
    </div >
  )
}

export default withToast(Home)